name: ci-pipeline
on:
  - push
jobs:
  CI_Integration:
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout stage
        uses: actions/checkout@v4

      - name: Setting up java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: running the build
        run: mvn clean package
      
      - name: uploading the artifact
        uses: actions/upload-artifact@v7
        with:
          name: userservice
          path: .target/userservice-0.0.1-SNAPSHOT.jar

      # https://github.com/marketplace/actions/dependency-check

      - name: running the OWASP dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env: 
          JAVA_HOME: /opt/jdk
        with:
          project: 'userservice'
          path: '.'
          format: 'HTML'
          out: 'reports'

          
      - name: uploading the artifact
        uses: actions/upload-artifact@v7
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

