name: ci-pipeline
on:
  - push
jobs:
  CI_Integration:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git checkout stage
        uses: actions/checkout@v4

      - name: Setting up java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: checking maven version
        run: mvn --version